export const COUNTRIES: { name: string; timezone: string; offset: number; icon: string }[] = [
  { name: 'Pakistan', timezone: 'Asia/Karachi', offset: 5, icon: '🇵🇰' },
  { name: 'UAE (Dubai)', timezone: 'Asia/Dubai', offset: 4, icon: '🇦🇪' },
  { name: 'Lebanon', timezone: 'Asia/Beirut', offset: 2, icon: '🇱🇧' },
  { name: 'United States (New York)', timezone: 'America/New_York', offset: -5, icon: '🇺🇸' },
  { name: 'United States (Los Angeles)', timezone: 'America/Los_Angeles', offset: -8, icon: '🇺🇸' },
  { name: 'United States (Chicago)', timezone: 'America/Chicago', offset: -6, icon: '🇺🇸' },
  { name: 'United Kingdom', timezone: 'Europe/London', offset: 0, icon: '🇬🇧' },
  { name: 'France', timezone: 'Europe/Paris', offset: 1, icon: '🇫🇷'  },
  { name: 'Germany', timezone: 'Europe/Berlin', offset: 1, icon: '🇩🇪' },
  { name: 'Spain', timezone: 'Europe/Madrid', offset: 1, icon: '🇪🇸' },
  { name: 'Italy', timezone: 'Europe/Rome', offset: 1, icon: '🇮🇹' },
  { name: 'Japan', timezone: 'Asia/Tokyo', offset: 9, icon: '🇯🇵' },
  { name: 'China', timezone: 'Asia/Shanghai', offset: 8, icon: '🇨🇳' },
  { name: 'India', timezone: 'Asia/Kolkata', offset: 5.5, icon: '🇮🇳' },
  { name: 'Australia (Sydney)', timezone: 'Australia/Sydney', offset: 11, icon: '🇦🇺' },
  { name: 'Australia (Melbourne)', timezone: 'Australia/Melbourne', offset: 11, icon: '🇦🇺' },
  { name: 'Brazil', timezone: 'America/Sao_Paulo', offset: -3, icon: '🇧🇷' },
  { name: 'Canada (Toronto)', timezone: 'America/Toronto', offset: -5, icon: '🇨🇦' },
  { name: 'Mexico', timezone: 'America/Mexico_City', offset: -6, icon: '🇲🇽' },
  { name: 'Russia (Moscow)', timezone: 'Europe/Moscow', offset: 3, icon: '🇷🇺' },
  { name: 'South Korea', timezone: 'Asia/Seoul', offset: 9, icon: '🇰🇷' },
  { name: 'Singapore', timezone: 'Asia/Singapore', offset: 8, icon: '🇸🇬' },
  { name: 'South Africa', timezone: 'Africa/Johannesburg', offset: 2, icon: '🇿🇦' },
  { name: 'Argentina', timezone: 'America/Argentina/Buenos_Aires', offset: -3, icon: '🇦🇷' },
  { name: 'New Zealand', timezone: 'Pacific/Auckland', offset: 13, icon: '🇳🇿' },
  { name: 'Thailand', timezone: 'Asia/Bangkok', offset: 7, icon: '🇹🇭' },
  { name: 'Indonesia (Jakarta)', timezone: 'Asia/Jakarta', offset: 7, icon: '🇮🇩' },
  { name: 'Philippines', timezone: 'Asia/Manila', offset: 8, icon: '🇵🇭' },
  { name: 'Vietnam', timezone: 'Asia/Ho_Chi_Minh', offset: 7, icon: '🇻🇳' },
  { name: 'Turkey', timezone: 'Europe/Istanbul', offset: 3, icon: '🇹🇷' },
  { name: 'Egypt', timezone: 'Africa/Cairo', offset: 2, icon: '🇪🇬' },
  { name: 'Israel', timezone: 'Asia/Jerusalem', offset: 2, icon: '🇮🇱' },
];

export const DEFAULT_COUNTRIES = COUNTRIES.slice(0, 5);