import type { CountryType } from "@/components/WorldTime/index.type";

export const COUNTRIES: CountryType[] = [
  {
    name: "Pakistan",
    timezone: "Asia/Karachi",
    offset: 5,
    icon: "🇵🇰",
    currency: { code: "pkr", name: "Pakistani Rupee", symbol: "Rs" },
  },
  {
    name: "UAE (Dubai)",
    timezone: "Asia/Dubai",
    offset: 4,
    icon: "🇦🇪",
    currency: { code: "aed", name: "UAE Dirham", symbol: "د.إ" },
  },
  {
    name: "Lebanon",
    timezone: "Asia/Beirut",
    offset: 2,
    icon: "🇱🇧",
    currency: { code: "lbp", name: "Lebanese Pound", symbol: "ل.ل" },
  },
  {
    name: "United States (New York)",
    timezone: "America/New_York",
    offset: -5,
    icon: "🇺🇸",
    currency: { code: "usd", name: "US Dollar", symbol: "$" },
  },
  {
    name: "United States (Los Angeles)",
    timezone: "America/Los_Angeles",
    offset: -8,
    icon: "🇺🇸",
    currency: { code: "usd", name: "US Dollar", symbol: "$" },
  },
  {
    name: "United States (Chicago)",
    timezone: "America/Chicago",
    offset: -6,
    icon: "🇺🇸",
    currency: { code: "usd", name: "US Dollar", symbol: "$" },
  },
  {
    name: "United Kingdom",
    timezone: "Europe/London",
    offset: 0,
    icon: "🇬🇧",
    currency: { code: "gbp", name: "British Pound", symbol: "£" },
  },
  {
    name: "France",
    timezone: "Europe/Paris",
    offset: 1,
    icon: "🇫🇷",
    currency: { code: "eur", name: "Euro", symbol: "€" },
  },
  {
    name: "Germany",
    timezone: "Europe/Berlin",
    offset: 1,
    icon: "🇩🇪",
    currency: { code: "eur", name: "Euro", symbol: "€" },
  },
  {
    name: "Spain",
    timezone: "Europe/Madrid",
    offset: 1,
    icon: "🇪🇸",
    currency: { code: "eur", name: "Euro", symbol: "€" },
  },
  {
    name: "Italy",
    timezone: "Europe/Rome",
    offset: 1,
    icon: "🇮🇹",
    currency: { code: "eur", name: "Euro", symbol: "€" },
  },
  {
    name: "Japan",
    timezone: "Asia/Tokyo",
    offset: 9,
    icon: "🇯🇵",
    currency: { code: "jpy", name: "Japanese Yen", symbol: "¥" },
  },
  {
    name: "China",
    timezone: "Asia/Shanghai",
    offset: 8,
    icon: "🇨🇳",
    currency: { code: "cny", name: "Chinese Yuan", symbol: "¥" },
  },
  {
    name: "India",
    timezone: "Asia/Kolkata",
    offset: 5.5,
    icon: "🇮🇳",
    currency: { code: "inr", name: "Indian Rupee", symbol: "₹" },
  },
  {
    name: "Australia (Sydney)",
    timezone: "Australia/Sydney",
    offset: 11,
    icon: "🇦🇺",
    currency: { code: "aud", name: "Australian Dollar", symbol: "A$" },
  },
  {
    name: "Australia (Melbourne)",
    timezone: "Australia/Melbourne",
    offset: 11,
    icon: "🇦🇺",
    currency: { code: "aud", name: "Australian Dollar", symbol: "A$" },
  },
  {
    name: "Brazil",
    timezone: "America/Sao_Paulo",
    offset: -3,
    icon: "🇧🇷",
    currency: { code: "brl", name: "Brazilian Real", symbol: "R$" },
  },
  {
    name: "Canada (Toronto)",
    timezone: "America/Toronto",
    offset: -5,
    icon: "🇨🇦",
    currency: { code: "cad", name: "Canadian Dollar", symbol: "C$" },
  },
  {
    name: "Mexico",
    timezone: "America/Mexico_City",
    offset: -6,
    icon: "🇲🇽",
    currency: { code: "mxn", name: "Mexican Peso", symbol: "$" },
  },
  {
    name: "Russia (Moscow)",
    timezone: "Europe/Moscow",
    offset: 3,
    icon: "🇷🇺",
    currency: { code: "rub", name: "Russian Ruble", symbol: "₽" },
  },
  {
    name: "South Korea",
    timezone: "Asia/Seoul",
    offset: 9,
    icon: "🇰🇷",
    currency: { code: "krw", name: "South Korean Won", symbol: "₩" },
  },
  {
    name: "Singapore",
    timezone: "Asia/Singapore",
    offset: 8,
    icon: "🇸🇬",
    currency: { code: "sgd", name: "Singapore Dollar", symbol: "S$" },
  },
  {
    name: "South Africa",
    timezone: "Africa/Johannesburg",
    offset: 2,
    icon: "🇿🇦",
    currency: { code: "zar", name: "South African Rand", symbol: "R" },
  },
  {
    name: "Argentina",
    timezone: "America/Argentina/Buenos_Aires",
    offset: -3,
    icon: "🇦🇷",
    currency: { code: "ars", name: "Argentine Peso", symbol: "$" },
  },
  {
    name: "New Zealand",
    timezone: "Pacific/Auckland",
    offset: 13,
    icon: "🇳🇿",
    currency: { code: "nzd", name: "New Zealand Dollar", symbol: "NZ$" },
  },
  {
    name: "Thailand",
    timezone: "Asia/Bangkok",
    offset: 7,
    icon: "🇹🇭",
    currency: { code: "thb", name: "Thai Baht", symbol: "฿" },
  },
  {
    name: "Indonesia (Jakarta)",
    timezone: "Asia/Jakarta",
    offset: 7,
    icon: "🇮🇩",
    currency: { code: "idr", name: "Indonesian Rupiah", symbol: "Rp" },
  },
  {
    name: "Philippines",
    timezone: "Asia/Manila",
    offset: 8,
    icon: "🇵🇭",
    currency: { code: "php", name: "Philippine Peso", symbol: "₱" },
  },
  {
    name: "Vietnam",
    timezone: "Asia/Ho_Chi_Minh",
    offset: 7,
    icon: "🇻🇳",
    currency: { code: "vnd", name: "Vietnamese Dong", symbol: "₫" },
  },
  {
    name: "Turkey",
    timezone: "Europe/Istanbul",
    offset: 3,
    icon: "🇹🇷",
    currency: { code: "try", name: "Turkish Lira", symbol: "₺" },
  },
  {
    name: "Egypt",
    timezone: "Africa/Cairo",
    offset: 2,
    icon: "🇪🇬",
    currency: { code: "egp", name: "Egyptian Pound", symbol: "E£" },
  },
  {
    name: "Israel",
    timezone: "Asia/Jerusalem",
    offset: 2,
    icon: "🇮🇱",
    currency: { code: "ils", name: "Israeli Shekel", symbol: "₪" },
  },
];

export const DEFAULT_COUNTRIES = COUNTRIES.slice(0, 5);
