import type { CountryType } from "@/components/WorldTime/index.type";

export const COUNTRIES: CountryType[] = [
  {
    name: "Pakistan",
    code: "PK",
    timezone: "Asia/Karachi",
    offset: 5,
    icon: "🇵🇰",
    currency: { code: "pkr", name: "Pakistani Rupee" },
  },
  {
    name: "UAE (Dubai)",
    code: "AE",
    timezone: "Asia/Dubai",
    offset: 4,
    icon: "🇦🇪",
    currency: { code: "aed", name: "UAE Dirham" },
  },
  {
    name: "Lebanon",
    code: "LB",
    timezone: "Asia/Beirut",
    offset: 2,
    icon: "🇱🇧",
    currency: { code: "lbp", name: "Lebanese Pound" },
  },
  {
    name: "United States (New York)",
    code: "US",
    timezone: "America/New_York",
    offset: -5,
    icon: "🇺🇸",
    currency: { code: "usd", name: "US Dollar" },
  },
  {
    name: "United States (Los Angeles)",
    code: "US",
    timezone: "America/Los_Angeles",
    offset: -8,
    icon: "🇺🇸",
    currency: { code: "usd", name: "US Dollar" },
  },
  {
    name: "United States (Chicago)",
    code: "US",
    timezone: "America/Chicago",
    offset: -6,
    icon: "🇺🇸",
    currency: { code: "usd", name: "US Dollar" },
  },
  {
    name: "United Kingdom",
    code: "GB",
    timezone: "Europe/London",
    offset: 0,
    icon: "🇬🇧",
    currency: { code: "gbp", name: "British Pound" },
  },
  {
    name: "France",
    code: "FR",
    timezone: "Europe/Paris",
    offset: 1,
    icon: "🇫🇷",
    currency: { code: "eur", name: "Euro" },
  },
  {
    name: "Germany",
    code: "DE",
    timezone: "Europe/Berlin",
    offset: 1,
    icon: "🇩🇪",
    currency: { code: "eur", name: "Euro" },
  },
  {
    name: "Spain",
    code: "ES",
    timezone: "Europe/Madrid",
    offset: 1,
    icon: "🇪🇸",
    currency: { code: "eur", name: "Euro" },
  },
  {
    name: "Italy",
    code: "IT",
    timezone: "Europe/Rome",
    offset: 1,
    icon: "🇮🇹",
    currency: { code: "eur", name: "Euro" },
  },
  {
    name: "Japan",
    code: "JP",
    timezone: "Asia/Tokyo",
    offset: 9,
    icon: "🇯🇵",
    currency: { code: "jpy", name: "Japanese Yen" },
  },
  {
    name: "China",
    code: "CN",
    timezone: "Asia/Shanghai",
    offset: 8,
    icon: "🇨🇳",
    currency: { code: "cny", name: "Chinese Yuan" },
  },
  {
    name: "India",
    code: "IN",
    timezone: "Asia/Kolkata",
    offset: 5.5,
    icon: "🇮🇳",
    currency: { code: "inr", name: "Indian Rupee" },
  },
  {
    name: "Australia (Sydney)",
    code: "AU",
    timezone: "Australia/Sydney",
    offset: 11,
    icon: "🇦🇺",
    currency: { code: "aud", name: "Australian Dollar" },
  },
  {
    name: "Australia (Melbourne)",
    code: "AU",
    timezone: "Australia/Melbourne",
    offset: 11,
    icon: "🇦🇺",
    currency: { code: "aud", name: "Australian Dollar" },
  },
  {
    name: "Brazil",
    code: "BR",
    timezone: "America/Sao_Paulo",
    offset: -3,
    icon: "🇧🇷",
    currency: { code: "brl", name: "Brazilian Real" },
  },
  {
    name: "Canada (Toronto)",
    code: "CA",
    timezone: "America/Toronto",
    offset: -5,
    icon: "🇨🇦",
    currency: { code: "cad", name: "Canadian Dollar" },
  },
  {
    name: "Mexico",
    code: "MX",
    timezone: "America/Mexico_City",
    offset: -6,
    icon: "🇲🇽",
    currency: { code: "mxn", name: "Mexican Peso" },
  },
  {
    name: "Russia (Moscow)",
    code: "RU",
    timezone: "Europe/Moscow",
    offset: 3,
    icon: "🇷🇺",
    currency: { code: "rub", name: "Russian Ruble" },
  },
  {
    name: "South Korea",
    code: "KR",
    timezone: "Asia/Seoul",
    offset: 9,
    icon: "🇰🇷",
    currency: { code: "krw", name: "South Korean Won" },
  },
  {
    name: "Singapore",
    code: "SG",
    timezone: "Asia/Singapore",
    offset: 8,
    icon: "🇸🇬",
    currency: { code: "sgd", name: "Singapore Dollar" },
  },
  {
    name: "South Africa",
    code: "ZA",
    timezone: "Africa/Johannesburg",
    offset: 2,
    icon: "🇿🇦",
    currency: { code: "zar", name: "South African Rand" },
  },
  {
    name: "Argentina",
    code: "AR",
    timezone: "America/Argentina/Buenos_Aires",
    offset: -3,
    icon: "🇦🇷",
    currency: { code: "ars", name: "Argentine Peso" },
  },
  {
    name: "New Zealand",
    code: "NZ",
    timezone: "Pacific/Auckland",
    offset: 13,
    icon: "🇳🇿",
    currency: { code: "nzd", name: "New Zealand Dollar" },
  },
  {
    name: "Thailand",
    code: "TH",
    timezone: "Asia/Bangkok",
    offset: 7,
    icon: "🇹🇭",
    currency: { code: "thb", name: "Thai Baht" },
  },
  {
    name: "Indonesia (Jakarta)",
    code: "ID",
    timezone: "Asia/Jakarta",
    offset: 7,
    icon: "🇮🇩",
    currency: { code: "idr", name: "Indonesian Rupiah" },
  },
  {
    name: "Philippines",
    code: "PH",
    timezone: "Asia/Manila",
    offset: 8,
    icon: "🇵🇭",
    currency: { code: "php", name: "Philippine Peso" },
  },
  {
    name: "Vietnam",
    code: "VN",
    timezone: "Asia/Ho_Chi_Minh",
    offset: 7,
    icon: "🇻🇳",
    currency: { code: "vnd", name: "Vietnamese Dong" },
  },
  {
    name: "Turkey",
    code: "TR",
    timezone: "Europe/Istanbul",
    offset: 3,
    icon: "🇹🇷",
    currency: { code: "try", name: "Turkish Lira" },
  },
  {
    name: "Egypt",
    code: "EG",
    timezone: "Africa/Cairo",
    offset: 2,
    icon: "🇪🇬",
    currency: { code: "egp", name: "Egyptian Pound" },
  },
  {
    name: "Israel",
    code: "IL",
    timezone: "Asia/Jerusalem",
    offset: 2,
    icon: "🇮🇱",
    currency: { code: "ils", name: "Israeli Shekel" },
  },
];

export const DEFAULT_COUNTRIES = COUNTRIES.slice(0, 5);
