import { type CurrencyType } from "@/components/WorldTime/index.type";

export const CURRENCIES: CurrencyType[] = [
  { code: "usd", name: "US Dollar", symbol: "$" },
  { code: "eur", name: "Euro", symbol: "€" },
  { code: "gbp", name: "British Pound", symbol: "£" },
  { code: "jpy", name: "Japanese Yen", symbol: "¥" },
  { code: "aud", name: "Australian Dollar", symbol: "A$" },
  { code: "cad", name: "Canadian Dollar", symbol: "C$" },
  { code: "chf", name: "Swiss Franc", symbol: "Fr" },
  { code: "cny", name: "Chinese Yuan", symbol: "¥" },
  { code: "inr", name: "Indian Rupee", symbol: "₹" },
  { code: "pkr", name: "Pakistani Rupee", symbol: "Rs" },
  { code: "aed", name: "UAE Dirham", symbol: "د.إ" },
  { code: "lbp", name: "Lebanese Pound", symbol: "ل.ل" },
  { code: "brl", name: "Brazilian Real", symbol: "R$" },
  { code: "mxn", name: "Mexican Peso", symbol: "$" },
  { code: "rub", name: "Russian Ruble", symbol: "₽" },
  { code: "krw", name: "South Korean Won", symbol: "₩" },
  { code: "sgd", name: "Singapore Dollar", symbol: "S$" },
  { code: "zar", name: "South African Rand", symbol: "R" },
  { code: "ars", name: "Argentine Peso", symbol: "$" },
  { code: "nzd", name: "New Zealand Dollar", symbol: "NZ$" },
  { code: "thb", name: "Thai Baht", symbol: "฿" },
  { code: "idr", name: "Indonesian Rupiah", symbol: "Rp" },
  { code: "php", name: "Philippine Peso", symbol: "₱" },
  { code: "vnd", name: "Vietnamese Dong", symbol: "₫" },
  { code: "try", name: "Turkish Lira", symbol: "₺" },
  { code: "egp", name: "Egyptian Pound", symbol: "E£" },
  { code: "ils", name: "Israeli Shekel", symbol: "₪" },
  { code: "sek", name: "Swedish Krona", symbol: "kr" },
  { code: "nok", name: "Norwegian Krone", symbol: "kr" },
  { code: "dkk", name: "Danish Krone", symbol: "kr" },
  { code: "pln", name: "Polish Zloty", symbol: "zł" },
  { code: "hkd", name: "Hong Kong Dollar", symbol: "HK$" },
  { code: "myr", name: "Malaysian Ringgit", symbol: "RM" },
  { code: "sar", name: "Saudi Riyal", symbol: "﷼" },
  { code: "clp", name: "Chilean Peso", symbol: "$" },
  { code: "cop", name: "Colombian Peso", symbol: "$" },
  { code: "ngn", name: "Nigerian Naira", symbol: "₦" },
  { code: "kes", name: "Kenyan Shilling", symbol: "KSh" },
];

export const DEFAULT_CURRENCIES: CurrencyType[] = [
  { code: "usd", name: "US Dollar", symbol: "$" },
  { code: "eur", name: "Euro", symbol: "€" },
  { code: "gbp", name: "British Pound", symbol: "£" },
];
