import { type CurrencyType } from "@/components/WorldTime/index.type";

export const CURRENCIES: CurrencyType[] = [
  { code: "usd", name: "US Dollar" },
  { code: "eur", name: "Euro" },
  { code: "gbp", name: "British Pound" },
  { code: "jpy", name: "Japanese Yen" },
  { code: "aud", name: "Australian Dollar" },
  { code: "cad", name: "Canadian Dollar" },
  { code: "chf", name: "Swiss Franc" },
  { code: "cny", name: "Chinese Yuan" },
  { code: "inr", name: "Indian Rupee" },
  { code: "pkr", name: "Pakistani Rupee" },
  { code: "aed", name: "UAE Dirham" },
  { code: "lbp", name: "Lebanese Pound" },
  { code: "brl", name: "Brazilian Real" },
  { code: "mxn", name: "Mexican Peso" },
  { code: "rub", name: "Russian Ruble" },
  { code: "krw", name: "South Korean Won" },
  { code: "sgd", name: "Singapore Dollar" },
  { code: "zar", name: "South African Rand" },
  { code: "ars", name: "Argentine Peso" },
  { code: "nzd", name: "New Zealand Dollar" },
  { code: "thb", name: "Thai Baht" },
  { code: "idr", name: "Indonesian Rupiah" },
  { code: "php", name: "Philippine Peso" },
  { code: "vnd", name: "Vietnamese Dong" },
  { code: "try", name: "Turkish Lira" },
  { code: "egp", name: "Egyptian Pound" },
  { code: "ils", name: "Israeli Shekel" },
  { code: "sek", name: "Swedish Krona" },
  { code: "nok", name: "Norwegian Krone" },
  { code: "dkk", name: "Danish Krone" },
  { code: "pln", name: "Polish Zloty" },
  { code: "hkd", name: "Hong Kong Dollar" },
  { code: "myr", name: "Malaysian Ringgit" },
  { code: "sar", name: "Saudi Riyal" },
  { code: "clp", name: "Chilean Peso" },
  { code: "cop", name: "Colombian Peso" },
  { code: "ngn", name: "Nigerian Naira" },
  { code: "kes", name: "Kenyan Shilling" },
];

export const DEFAULT_CURRENCIES: CurrencyType[] = [
  { code: "usd", name: "US Dollar" },
  { code: "eur", name: "Euro" },
  { code: "gbp", name: "British Pound" },
];
